name: Deploy to Skynet
on:
  pull_request:
jobs:
  build:
  runs-on: ubuntu-latest
steps:
  — uses: actions/checkout@v2
  — name: Use Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 14.x
  - name: Install dependencies
    run: npm install
  - name: Run unit tests
    run: npm test
  - name: Build
    run: npm run build